### ISSUE TITLE
Vipps 1.3.1 Not working with 2.3.0

### ISSUE THREAD

**Issue by DigiBlooD** [vippsas/vipps-magento#31]
Hi

1.3.1 install breaks clean magento 2.3.0 install. 

`[xxx@xxx xxx]$ composer require vipps/module-payment
Using version ^1.3 for vipps/module-payment
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing vipps/module-payment (1.3.1): Loading from cache
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
[xxx@xxx xxx]$ php bin/magento module:enable Vipps_Payment
The following modules have been enabled:
- Vipps_Payment

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:enable' with the --clear-static-content option to clear them.
[xxx@xxx xxx]$ php bin/magento setup:upgrade
[xxx@xxx xxx]$`

all magento commands just give a new bash line when commands are run. Log tells us nothing, no errors no nothing.

PHP v7.1.27
Apache v2.4.37
MySQL v10.1.37-MariaDB-cll-lve

Suggestions on getting it working? Had it working on 2.2.6, 2.2.7 but not on 2.3.0. Live store is already updated to 2.3.0 since we had other reasons for upgrading. Our copy of the live store also breaks with this version.

--
DigiBlooD

**Comment by aluminium1989** [comment]
Hi @DigiBlooD 
Please try to install the new module version - 1.3.2 ?
It contains the fix for PHP7.1

**Comment by DigiBlooD** [comment]
Thanks for the 1.3.2 version. New issue se picture and log.

![image](https://user-images.githubusercontent.com/41118712/55577139-2186fa80-5713-11e9-867d-4c59c9368add.png)

`[2019-04-04 17:50:17] vipps.DEBUG: Fetched payment details [] []
[2019-04-04 17:51:42] vipps.CRITICAL: Invalid header line detected [] []
[2019-04-04 17:51:42] vipps.CRITICAL: Vipps\Payment\Gateway\Exception\AuthenticationException: Kan ikke hente access token fra Vipps. in /home/xxx/xxx/vendor/vipps/module-payment/Model/TokenProvider.php:193
Stack trace:
#0 /home/xxx/xxx/vendor/vipps/module-payment/Model/TokenProvider.php(153): Vipps\Payment\Model\TokenProvider->readJwt()
#1 /home/xxx/xxx/vendor/vipps/module-payment/Model/TokenProvider.php(125): Vipps\Payment\Model\TokenProvider->regenerate()
#2 /home/xxx/xxx/vendor/vipps/module-payment/Gateway/Http/Client/Curl.php(156): Vipps\Payment\Model\TokenProvider->get()
#3 /home/xxx/xxx/vendor/vipps/module-payment/Gateway/Http/Client/Curl.php(133): Vipps\Payment\Gateway\Http\Client\Curl->getHeaders(Array)
#4 /home/xxx/xxx/vendor/vipps/module-payment/Gateway/Http/Client/Curl.php(92): Vipps\Payment\Gateway\Http\Client\Curl->place(Object(Magento\Payment\Gateway\Http\Transfer))
#5 /home/xxx/xxx/vendor/vipps/module-payment/Gateway/Command/GatewayCommand.php(139): Vipps\Payment\Gateway\Http\Client\Curl->placeRequest(Object(Magento\Payment\Gateway\Http\Transfer))
#6 /home/xxx/xxx/vendor/magento/module-payment/Gateway/Command/CommandManager.php(65): Vipps\Payment\Gateway\Command\GatewayCommand->execute(Array)
#7 /home/xxx/xxx/vendor/vipps/module-payment/Gateway/Command/CommandManager.php(132): Magento\Payment\Gateway\Command\CommandManager->executeByCode('initiate', Object(Magento\Quote\Model\Quote\Payment), Array)
#8 /home/xxx/xxx/vendor/vipps/module-payment/Gateway/Command/CommandManager.php(59): Vipps\Payment\Gateway\Command\CommandManager->executeByCode('initiate', Object(Magento\Quote\Model\Quote\Payment), Array)
#9 /home/xxx/xxx/vendor/vipps/module-payment/Controller/Payment/Regular.php(86): Vipps\Payment\Gateway\Command\CommandManager->initiatePayment(Object(Magento\Quote\Model\Quote\Payment), Array)
#10 /home/xxx/xxx/generated/code/Vipps/Payment/Controller/Payment/Regular/Interceptor.php(24): Vipps\Payment\Controller\Payment\Regular->execute()
#11 /home/xxx/xxx/vendor/magento/framework/App/Action/Action.php(108): Vipps\Payment\Controller\Payment\Regular\Interceptor->execute()
#12 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(138): Vipps\Payment\Controller\Payment\Regular\Interceptor->___callParent('dispatch', Array)
#14 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(153): Vipps\Payment\Controller\Payment\Regular\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /home/xxx/xxx/generated/code/Vipps/Payment/Controller/Payment/Regular/Interceptor.php(39): Vipps\Payment\Controller\Payment\Regular\Interceptor->___callPlugins('dispatch', Array, Array)
#16 /home/xxx/xxx/vendor/magento/framework/App/FrontController.php(159): Vipps\Payment\Controller\Payment\Regular\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /home/xxx/xxx/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Vipps\Payment\Controller\Payment\Regular\Interceptor))
#18 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#20 /home/xxx/xxx/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /home/xxx/xxx/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /home/xxx/xxx/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(135): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /home/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /home/xxx/xxx/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#28 /home/xxx/xxx/vendor/magento/framework/App/Http.php(136): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /home/xxx/xxx/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#30 /home/xxx/xxx/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#31 /home/xxx/xxx/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#32 {main} [] []
[2019-04-04 17:51:42] vipps.CRITICAL: Kan ikke hente access token fra Vipps. [] []`

I have only been able to test from our testweb. Can this be related that we are trying with the Saleunit Serial Number, Client ID, Client Secret, Sub key 1 & 2 ment for our live domain (Vipps not active there)? If you think its related we can try running it live on the live store but not before. ;)

Not able to find any other errors (apache etc.)

--
DigiBlooD

**Comment by DigiBlooD** [comment]
Btw, is there any information on how to cleanup after Vipps when removing it (db, etc)? Would really love to clean install it on the live store.

--
DigiBlooD

**Comment by aluminium1989** [comment]
Hi @DigiBlooD.

Vipps module requires your website to be accessible from the internet. So probably that's the reason why token is not given you by Vipps.

Automatic module uninstall is not implemented yet.
To remove module tables from the database you need to drop these tables with the command:
`DROP TABLE IF EXISTS vipps_payment_jwt, vipps_profiling, vipps_quote_attempt, vipps_quote;`
To remove module's configuration perform this query:
`DELETE * FROM core_config_data where path like '%payment/vipps%' `

**Comment by aluminium1989** [comment]
Hi @DigiBlooD.
Did you try Vipps module on live server?
Please let me know how it goes.

**Comment by aluminium1989** [comment]
Closing this issue, as there has been no activity for two weeks
